# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170220_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemborrowed',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemborrowed',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
