# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='times_borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
